### DISCUSSION TITLE
`rye sync` fails in CI but not locally (PyPy3)

### DISCUSSION THREAD

**Discussion by SichangHe** [astral-sh/rye#1071] [Q&A] [answered]
`rye sync` [failed in my CI](https://github.com/SichangHe/internet_route_verification/actions/runs/9040005148/job/24843629471):

```sh
Run rye sync
  rye sync
  shell: /usr/bin/bash -e {0}
  env:
    RYE_HOME: /opt/hostedtoolcache/setup-rye-2024-03-04/0.33.0/x86_64
Downloading pypy@3.10.13
Checking checksum
Unpacking
Downloaded pypy@3.10.13
Reusing already existing virtualenv
Generating production lockfile: /home/runner/work/internet_route_verification/internet_route_verification/rpsl_lexer/requirements.lock
Creating virtualenv for pip-tools
Generating dev lockfile: /home/runner/work/internet_route_verification/internet_route_verification/rpsl_lexer/requirements-dev.lock
Installing dependencies
error: could not locate pip

Caused by:
    no site-packages in venv
```

But, when I test it locally, it works:

```sh
$ rye sync
Downloading pypy@3.10.13
Checking checksum
Unpacking
Downloaded pypy@3.10.13
Initializing new virtualenv in /home/sichanghe/internet_route_verification/rpsl_lexer/.venv
Python version: pypy@3.10.13
Generating production lockfile: /home/sichanghe/internet_route_verification/rpsl_lexer/requirements.lock
Generating dev lockfile: /home/sichanghe/internet_route_verification/rpsl_lexer/requirements-dev.lock
Installing dependencies
   Built file:///home/sichanghe/internet_route_verification/rpsl_lexer                                                                                                    Built 1 editable in 796ms
Resolved 2 packages in 2ms
Downloaded 2 packages in 1.48s
Installed 8 packages in 8ms
 + exceptiongroup==1.2.1
 + iniconfig==2.0.0
 + packaging==24.0
 + pluggy==1.5.0
 + pyparsing==3.1.2
 + pytest==8.2.0
 + rpsl-lexer==0.2.0 (from file:///home/sichanghe/internet_route_verification/rpsl_lexer)
 + tomli==2.0.1
Done!
```

This is my CI file:

```yml
on:
  push:
    paths:
      - ".github/workflows/python.yml"
      - "**.py"
jobs:
  python:
    name: Python checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: eifinger/setup-rye@v2
        with:
          enable-cache: true
          working-directory: rpsl_lexer/
      - run: rye sync
        working-directory: rpsl_lexer/
      - run: rye test
        working-directory: rpsl_lexer/
      - run: rye format --check
        working-directory: rpsl_lexer/
```

Not sure what is wrong. Any ideas?
