### DISCUSSION TITLE
Is is possible to get autocompletion with rye scripts?

### DISCUSSION THREAD

**Discussion by asmith26** [astral-sh/rye#1140] [Q&A]
Hi there, Just wondering, is it possible to get auto completion when using rye scripts? E.g. if my script looks like those at https://rye.astral.sh/guide/pyproject/#toolryescripts

```toml
[tool.rye.scripts]
devserver = "flask run --app ./hello.py --debug"
```

Am I able to add something (e.g. maybe https://rye.astral.sh/guide/installation/#shell-completion) to get tab completion if I type `rye run d + TAB`? (I'm using `zsh`)

Thanks for any help!
