### DISCUSSION TITLE
Is it possible to chain `rye` commands in rye scripts?

### DISCUSSION THREAD

**Discussion by asmith26** [astral-sh/rye#1142] [Q&A]
E.g

```toml
[tool.rye.scripts]
checks = { chain = ["rye lint", "rye fmt --check"] }
```

When I run, I get:

```bash
$ rye run checks
error: invalid or unknown script 'rye'
```

Thanks!

---

Related: https://github.com/astral-sh/rye/issues/1036
