### DISCUSSION TITLE
Synching vs Features in Workspaces

### DISCUSSION THREAD

**Discussion by mitsuhiko** [astral-sh/rye#122] [Q&A]
There is an issue which asks for `sync` to be implied (https://github.com/mitsuhiko/rye/issues/114). There is now also a flag called `--features` and `--all-features` on `sync`/`lock` to opt-in certain optional dependencies (https://github.com/mitsuhiko/rye/pull/121). I think it's a good time to think about how this can work.

The lockfile long term should work feature independent. That means that the lockfile is the same no matter which features are turned on. This is also how this works in Rust and I quite like that. So let's disregard the locking mechanism for now. The question however is about how the virtualenv is managed:

1. When you `sync` with `--features`, it remembers the state of the features turned on and next time running `sync` runs with the same features turned on.
2. When you `sync`, you need to always pass `--features` or it will install without optional features. That's also already the case with `--no-dev` which is needed explicitly to be passed to turn off the dev dependencies.
3. There is a `.rye.toml` file or a part in `pyproject.toml` which influences how `sync`/`lock` operate.

I'm a bit conflicted here. My hunch is that option 3 is probably the most sensible.

**Comment by T-256** [comment]
Hello Armin, thanks you for starting on simplify managing python projects. Here is my idea:

poetry/pdm/hatch supports multiple environments. why not rye?
this will add `--env` to cli commands and removes `--dev` from add/remove commands and `--no-dev` from sync command.

### Dev env:
adding and syncing (`--env=default` by default):
```zsh
rye add flask
rye add black --env=dev
rye add ruff --env=dev --optional=ruff
rye sync
rye sync --env=dev --all-features
```
`pyproject.toml`
```toml
[project]
name = "test-wsl"
version = "0.1.0"
description = "Add a short description here"
dependencies = ["flask~=2.3.2"]
readme = "README.md"
requires-python = ">= 3.8"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye.env.dev]
dependencies = ["black~=23.3.0"]
[tool.rye.env.dev.optional-dependencies]
ruff= ["ruff~=0.0.265"]
```

```
├── README.md
├── pyproject.toml
├── requirements-dev-ruff.lock
├── requirements-dev.lock               # default value of `feature` ignored
├── requirements.lock                   # default value of `feature` and `env` ignored
└── .venvs                              # {env}{feature}{toolchain}
    └── default-main-cpython_3.11.1
         └── bin
         └── lib/site-packages
              └── flask
    └── dev-main-cpython_3.11.1
         └── bin
         └── lib/site-packages
              └── flask
              └── black
    └── dev-ruff-cpython_3.11.1
         └── bin
         └── lib/site-packages
              └── flask
              └── black
              └── ruff
```

**Reply by T-256** [reply]
> 3\. There is a `.rye.toml` file or a part in `pyproject.toml` which influences how `sync`/`lock` operate.

if using this way, we also need a command:
```zsh
rye set sync --all-features
```

```toml
[tool.rye.args]
sync = ["all-features"]
```
and for reset using without any options:
```zsh
rye set sync
```
