### DISCUSSION TITLE
How to add a Spacy model to pyproject.toml

### DISCUSSION THREAD

**Discussion by cdolek** [astral-sh/rye#1387] [Q&A] [answered]
I would like to have a spacy model installed via rye. Normally, we would do this and it would be added:

```sh
rye run python -m spacy download en_core_web_sm
```
However, when you `sync`, rye uninstalls it.

Is there a way to specify this in `pyproject.toml` and keep it?

I tried adding the following with no luck:

```toml
[[tool.rye.sources]]
name="en_core_web_sm"
url="https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.7.1/en_core_web_sm-3.7.1-py3-none-any.whl"
```

Two other people asked about this here: https://github.com/astral-sh/rye/discussions/1004
