### DISCUSSION TITLE
Dedicated Action to setup-rye

### DISCUSSION THREAD

**Discussion by eifinger** [astral-sh/rye#364] [Show and tell]
I created dedicated Action to install rye: https://github.com/eifinger/setup-rye

```yaml
- name: Checkout your repository
  uses: actions/checkout@v3

- uses: eifinger/setup-rye@v1

- name: Sync your dependencies
  run: rye sync
```

I am using rye for some projects and really love the experience.
I had some trouble installing rye in GitHub Action runs, especially doing it performantly in self-hosted runners.

My plan is to offer the same experience as the [actions/setup-python](https://github.com/actions/setup-python) action. This means added functionality for caches etc.

I would be glad to receive feedback and improvement ideas via issues or PRs.

Hope this helps you in your daily happy programming activities ❤️
