### DISCUSSION TITLE
Possible to include package with different name to the project name?

### DISCUSSION THREAD

**Discussion by engeir** [astral-sh/rye#691] [Q&A]
With Poetry, I have a project name of `very-long-name` that I can publish and install as `pip install very-long-name`. The code is however stored in `src/vln`, and imported in the code as `import vln`.

I accomplish this in poetry using the `pyproject.toml` field described [here](https://python-poetry.org/docs/pyproject/#packages), as:

```toml
[tool.poetry]
...
name = "very-long-name"
packages = [{include="vln", from="src"}]
...
```

I still could not figure out how this might be done with rye, if it is?

I believe it the same question as asked [here](https://github.com/pypa/hatch/issues/899).
