### DISCUSSION TITLE
Define rye scripts with arguments passthrough?

### DISCUSSION THREAD

**Discussion by wgordon17** [astral-sh/rye#965] [Q&A]
Currently, when defining a rye script, it's just a static command. Is it possible to define a rye script that is able to take a list of arguments? Similar to PDM's arguments placeholder https://pdm-project.org/latest/usage/scripts/#arguments-placeholder?

**Comment by wgordon17** [comment]
I think this would _also_ be awesome for chained scripts

```
error: extra arguments to chained commands are not allowed
```

**Comment by Murtagy** [comment]
I agree, also passing env vars across the chain seems extremely useful.
e.g. I want to create a temporary database to run my test suite. To do that I run my regular app, but the database string points to a new temporary file. So before each test suite I remove the sqllite database from the previous run. Currently defining this seems a mess

**Comment by mitsuhiko** [comment]
Arguments can be passed:

```toml
[tool.rye.scripts]
foo = "python -c 'import sys; print(sys.argv)'"
```

```
C:\Temp\foo>rye run foo 1 2 3
['-c', '1', '2', '3']
```

Or do I misunderstand the request here?

**Reply by wgordon17** [reply]
There's a couple different use cases, plus limitations with the current implementation.

For example, using `pdm`'s syntax, I'm able to place the arguments _anywhere_ in my command, it just so happens all my use cases have them at the end 😅 But I'm _also_ able to specify default values, which is very useful for being able to call the command from my terminal for performing actions on _all_ files (my default) versus letting my IDE perform actions on a _specific_ file (the override). Finally, being able to pass arguments to composite commands, which is currently disallowed by the binary, so that I could (for instance) have a formatting command and a linting command, and then have a composite that runs both together. The same use case above of being able to specify a single file from my IDE for "on-save" type of events/triggers.

Perhaps, best of all, it would help to see a specific example

```toml
[tool.pdm.scripts]
# Default to linting the entire src/ directory, but allow overriding with specific files
ruff-check = "ruff check --fix --exit-zero {args:src/}"
ruff-format = "ruff format {args:src/}"
# Run both check and format in a single call
ruff-fix = {composite = ["ruff-check", "ruff-format"]}
```

The special `{args}` placeholder allows command arguments to be passed _through_ from the composite to the individual commands, and would also allow for placement of those arguments anywhere (if needed). Additionally, I'm able to specify a default `:src/` so that just running `pdm run ruff-fix` would take care of my whole directory, as opposed to my "on-save" trigger in PyCharm being `pdm run ruff-fix $FilePathRelativeToProjectRoot$` so that only my specific, single file gets updated.

I hope this helps further explain the request.
