### ISSUE TITLE
Generate requirement.lock may put `--index-url` line after `--extra-index-url` line, cause `pip install -r requirement.lock` ignore extra index url

### ISSUE THREAD

**Issue by zedongh** [astral-sh/rye#1012]
### Steps to Reproduce

Here are a open issue for pypi [--extra-index-url ignored if before --index-url in requirements.txt](https://github.com/pypa/pip/issues/11511) show why order of `extra-index-url` and `index-url` matters now.

```toml
[[tool.rye.sources]]
name = "pypi"
url = "https://mirrors.ustc.edu.cn/pypi/web/simple"

```

will cause requirement.lock
```
--extra-index-url https://mirrors.ustc.edu.cn/pypi/web/simple
--index-url https://pypi.org/pypi
```

and a temporay solution is declare default on the top of toml

```toml
[[tool.rye.sources]]
name = "default"
url = "https://pypi.org/pypi"

[[tool.rye.sources]]
name = "pypi"
url = "https://mirrors.ustc.edu.cn/pypi/web/simple"
```
will cause requirement.lock
```
--index-url https://pypi.org/pypi
--extra-index-url https://mirrors.ustc.edu.cn/pypi/web/simple
```

### Expected Result

For compatiable should always put `--index-url` line before `--extra-index-url` in generated `requirement.lock` and `requirement-dev.lock`

### Actual Result

`--index-url` line after `--extra-index-url` line if not declare top `default` source override

### Version Info

0.32.0

### Stacktrace

not necessary
