### ISSUE TITLE
`rye version` doesn't respect `dynamic = ['version']` setting

### ISSUE THREAD

**Issue by Aran-Fey** [astral-sh/rye#1028]
### Steps to Reproduce

1. Create a `pyproject.toml` with dynamic versioning:
    ```toml
[project]
dynamic = ["version"]
```
2. Use `rye version -b` to bump the version:
    ```bash
rye version -b patch
```

### Expected Result

The version gets bumped in the correct place, similar to what `hatch version` would do.

### Actual Result

The version gets written to the `pyproject.toml` file, resulting in:

```toml
[project]
dynamic = ["version"]
version = "1.2.3"
```

### Version Info

rye 0.32.0
commit: 0.32.0 (e1b4f2a29 2024-03-29)
platform: windows (x86_64)
self-python: cpython@3.12.2
symlink support: true
uv enabled: true
