### ISSUE TITLE
Ability to easily chain built-in rye commands, e.g., `rye lint`

### ISSUE THREAD

**Issue by linjer** [astral-sh/rye#1036]
Currently interested in chaining or extending the `rye lint` command to also perform typechecking. For example:

```toml
[tool.rye.scripts]
typecheck = "mypy mymodule"
check = { chain = ["rye lint", "typecheck"] }
linter = "lint"  # also fails
```

This seems to fail because `rye` is not available in the environment. I also could not find any documentation on if I could customize the `lint` command.

## Suggestion

Make rye native commands accessible to scripts.

**Comment by asmith26** [comment]
I would also find this helpful. An initial work around:

1. Install ruff `rye add --dev ruff`
2. Add to `pyproject.toml`
```toml
[tool.rye.scripts]
check-lint = "ruff check"
```

Related https://github.com/astral-sh/rye/discussions/1142

**Comment by jamesbraza** [comment]
Does `chain` do what you need? https://rye.astral.sh/guide/pyproject/#chain

```toml
# pyproject.toml

[tool.rye.scripts]
lint = { chain = ["lint:black", "lint:flake8"] }
"lint:black" = "black --check src"
"lint:flake8" = "flake8 src"
```

Then:

- `rye lint`: runs Ruff
- `rye run lint`: runs the above scripts
