### ISSUE TITLE
TOML parser raises when inline table is spread on multiple lines

### ISSUE THREAD

**Issue by baggiponte** [astral-sh/rye#1108]
### Steps to Reproduce

Define any script as inline table:

```toml
[tool.rye.scripts]
devserver = {
  cmd = "flask run --debug", env = { FLASK_APP = "./hello.py" }
}
```
### Expected Result

The server runs

### Actual Result

```bash
rye run devserver
error: failed to parse pyproject.toml (at '/blablabla/pyproject.toml')

Caused by:
    TOML parse error at line 40, column 8
       |
    40 | devserver = {
       |        ^
    invalid inline table
    expected `}`
```

### Version Info

rye 0.34.0
commit: 0.34.0 (d31340178 2024-05-20)
platform: macos (aarch64)
self-python: cpython@3.12.1
symlink support: true
uv enabled: true
