### ISSUE TITLE
Creating multiple lock files

### ISSUE THREAD

**Issue by djagoda881** [astral-sh/rye#1138]
Hello,
I'm using rye in repository when I have few optional dependencies group. I'm using this group depends on docker image that I want to create. So, for example:
```toml
[project]
name = "test"
version = "1.1.0"

dependencies = [
    "pandas>=2.2.2",
    "pyarrow>=16.1.0",
 
]
requires-python = ">=3.10"
readme = "README.md"

[project.optional-dependencies]

group1 = [
    "azure-core==1.30.1",
    "azure-storage-blob==12.20.0",
    "adlfs==2024.4.1",
]
group2 = [
    "awswrangler==3.7.3",
    "s3fs==2024.6.0",
]
```
I'd like to create my custom  `.lock` file which I can use in my docker image.
 It will be cool to have optional flag during execution of `rye lock --fatures group1`  for example `--lock-file` where I could specify new lock file with default dependencies and dependencies from group1. Whole command
 `rye lock --fatures group1 --lock-file requirements-group1`. Files in root repository folder after execution:
```bash
├── requirements-dev.lock
├── requirements-group1`.lock
├── requirements.lock
```
