### ISSUE TITLE
Pass coverage related arguments to pytest

### ISSUE THREAD

**Issue by m-rph** [astral-sh/rye#1146]
I'd like to be able to pass additional coverage related flags when running tests.
In particular, I'd like `--cov [package]`, `--cov-report`, `--cov-fail-under`. 

Alternatively, I'd like if possible to be able to just pass whatever subsequent arguments and just forward them to pytest.

**Comment by m-rph** [comment]
By the way, I wouldn't mind implementing this if the bandwidth isn't here.

**Comment by my1e5** [comment]
Isn't this already possible? See https://rye.astral.sh/guide/commands/test/ and `[EXTRA_ARGS]...`

Also you can add extra args in your `pyproject.toml` file. For example
```toml
[tool.pytest.ini_options]
addopts = "--cov=my project --cov-report html"
```

**Comment by m-rph** [comment]
Iugh, that's right, I missed the -- part— this is embarrassing... Feel free to close then.

**Comment by davehowell** [comment]
This issue can be closed, because the functionality exists and works well.


Just to clarify, this works (note the extra `--` in there is required):
`rye test -- --cov=src`

And if you have that config as @my1e5 listed above:

```toml
[tool.pytest.ini_options]
addopts = "--cov=src"
```
Then you can just do: `rye test` , and it will append those extra options to the command. Note that no extra `--` separator is required when using `addopts` from the config. 

This assumes that `src` is the directory path to your code. 

Also note that rye has exposed some options directly, e.g. you can do `rye test -v` OR you can do `rye test -- -v`. Both of these also work `rye test -v -- --cov=src` and `rye test -- -v --cov=src`

I went around in circles a bit with this. I was running `rye add --dev pytest pytest-cov` to add the packages, and then running `rye sync` removed the packages from the venv (and lockfile) because (I think) I had the `pyproject.toml` file open hence preventing `rye add` from updating the toml file, causing `rye sync` to revert to the wrong config. Note that you don't need to do `rye sync` when updating the `[tool.pytest.ini_options]` part of the pyproject.toml file, but likely do for other parts, like the build options and dependencies.

The above is totally user error, but if this happens to you (or future me) then check your pyproject.toml file is saved with something like this in it (versions notwithstanding):
```toml
[tool.rye]
managed = true
dev-dependencies = [
    "pytest>=8.3.3",
    "pytest-cov>=6.0.0",
]
```
