### ISSUE TITLE
Supports local dependencies by path in monorepo

### ISSUE THREAD

**Issue by boringplay** [astral-sh/rye#1179]
Supports local dependencies by path in monorepo.

```toml
[project]
name = "demo"
version = "0.1.0"
dependencies = ["some_local_pkt=../../xxxx"]
```
