### ISSUE TITLE
`IO error: not a terminal` in GitHub Actions from `rye publish`

### ISSUE THREAD

**Issue by jamesbraza** [astral-sh/rye#1258]
### Steps to Reproduce

I have a GitHub Action that looks like so with Python 3.12.4:

```yaml
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: eifinger/setup-rye@v4
        with:
          enable-cache: true
      - run: rye sync --no-lock
      - run: rye build --sdist --wheel
      - run: rye publish --token ${{ secrets.PYPI_API_TOKEN }}
```

When I run it, the `rye publish` step fails with `error: IO error: not a terminal`

### Expected Result

I expected this publish job to work

### Actual Result

The below error during `rye publish`:

```none
Run rye publish --token ***
  rye publish --token ***
  shell: /usr/bin/bash -e {0}
  env:
    RYE_HOME: /opt/hostedtoolcache/setup-rye-2024-03-04/0.37.0/x86_64

error: IO error: not a terminal

Caused by:
    not a terminal

Error: Process completed with exit code 1.
```

https://github.com/astral-sh/rye/issues/246 seems to have the same error

### Version Info

0.37.0 via https://github.com/eifinger/setup-rye

**Comment by jamesbraza** [comment]
Also cc @eifinger if he has seen this before

**Comment by eifinger** [comment]
> Also cc @eifinger if he has seen this before

I have not seen this before. I usually use [pypi-publish](https://github.com/pypa/gh-action-pypi-publish) to publish to PyPi.

Can you replace my action with

```yaml
run: curl -sSf https://rye-up.com/get | RYE_INSTALL_OPTION="--yes" bash
```

To make sure the bug is with `rye` itself instead of my action?

**Comment by jamesbraza** [comment]
Okay actually I am having a tough time getting the manual install to work. The URL you shared gives a "301 Moved Permanently" error. I am now using:

```yaml
    steps:
      - uses: actions/checkout@v4
      - run: |
          curl -sSf https://rye.astral.sh/get | RYE_INSTALL_OPTION="--yes" bash
          echo "$HOME/.rye/env" >> $GITHUB_PATH
      - run: rye sync --no-lock
```

But this still gives `line 1: rye: command not found` in the last `run` step. Do you know what I am doing wrong here?
