### ISSUE TITLE
Add `--find-link` flag to `rye install`

### ISSUE THREAD

**Issue by Maxi91f** [astral-sh/rye#1283]
We are using a local folder to store packages without a static html or pypi server for local development and CI.

On the `pyproyect.toml` we use something like this without any problem:

``` toml
[[tool.rye.sources]]
name = "local"
url = "file:/some/path"
type = "find-links"
``` 

But on some scenarios we need to run something equivalent to install a package as global tool, but we couldn't find a way to configure `rye install` to use `find-links`. I imagine the command could look something like this:

`rye install --path /some/path my_package --find-links`

Trying to run the same command without `--find-links` doesn't works on our case, because on the folder we only have the `.whl` files.

I apology in advance if this was already proposed.
