### ISSUE TITLE
Rye defaults to pypi regardless of configured custom servers.

### ISSUE THREAD

**Issue by narigama** [astral-sh/rye#1288]
### Steps to Reproduce

- Start up an instance of `pypiserver/pypiserver` using docker [0].
- Configure the instance in `$HOME/.rye/config.toml` as an additional source [1].
- `rye build --clean --wheel`
- `rye publish --repository foobar`

[0]
```
docker run --rm -d --name pypi -p 8080:8080 pypiserver/pypiserver
```

[1]
```toml
[[tool.rye.sources]]
name = "foobar"
url = "http://localhost:8080/simple/"
verify-ssl = false
```

### Expected Result

Rye should push a build to the custom pypi server.

### Actual Result

Rye defaults to pypi and asks for an access token.

```
$ rye publish --repository foobar
No access token found, generate one at: https://pypi.org/manage/account/token/
Access token:
```

### Version Info

rye 0.37.0
commit: 0.37.0 (09b67c469 2024-07-20)
platform: linux (x86_64)
self-python: cpython@3.12.3
symlink support: true
uv enabled: true
