### ISSUE TITLE
rye sync should support the attribute --index-url and --extra-index-url

### ISSUE THREAD

**Issue by Trusted97** [astral-sh/rye#1318]
Hello there!

I am working on a project using Rye, and I have encountered an issue with my CI setup in GitLab. One of the packages I need for testing is hosted in my private registry, which leads to the following error:

```
Forcing re-creation of non-rye managed virtualenv
Initializing new virtualenv in /builds/******/test-python-project/.venv
Python version: cpython@3.9.2
Installing dependencies
  × No solution found when resolving dependencies:
  ╰─▶ Because starwarspy was not found in the package registry and you
      require starwarspy==0.7.0, we can conclude that the requirements are
      unsatisfiable.
error: Installation of dependencies failed in venv at /builds/*****/test-python-project/.venv. uv exited with status: exit status: 1
```

This error occurs because the package starwarspy is not found in the public registry. In my local environment, I resolve this by configuring `~/.rye/config.toml` with the necessary private registry sources, and everything works fine. However, for security reasons, I cannot update the config.toml file on my CI runner.

It would be helpful if the `rye sync` command could accept an --extra-index-url parameter during the synchronization process.

My current CI job script looks like this:
 
 ```
package::test:
  stage: test
  image: xxxx-xxxx-xxxx/python:$PYTHON_VERSION-uv-rye
  script:
    - uv venv
    - uv sync --extra-index-url https://gitlab-ci-token:$CI_JOB_TOKEN@XXXXXXX/api/v4/projects/XXXXX/packages/pypi/simple
    - source $VENV_DIR/bin/activate
    - rye sync -f
    - rye test
```

I've tried to create the virtual environment with uv and sync the dependencies, and I see that starwarspy is correctly downloaded. However, when I try to run rye sync, it gives me the same error as before because Rye doesn't know how to resolve starwarspy.

Do you have any suggestions for this kind of problem?

**Comment by bluss** [comment]
For this case, is it acceptable to use a combination of config and environment variables? There should be an example here https://rye.astral.sh/guide/sources/#index-authentication

**Comment by Trusted97** [comment]
So, you're suggesting adding the following lines to the `pyproject.toml` of the repository:

```
[[sources]]
name = "gitlab-private-registry"
url = "https://${TOKEN_NAME}:${TOKEN_PASSWORD}@xxxxxxxx/pypi/simple/"
```

I believe this might work, but it feels like an "ugly" solution because it forces me to add these lines to every repository that needs this package.

I'll give a try to see if works

**Comment by bluss** [comment]
I don't know any option for index (like rye sync doesn't seem to have it). I would explore uv's help and docs, maybe they have an environment variable for extra index that you can set.

Sources could possibly added (to config) through `rye config` using the cli, not sure if that helps.

**Comment by Trusted97** [comment]
I've found a hacky and ugly solution:

``` 
package::test:
  stage: test
  image: XXXXXXXX/python:$PYTHON_VERSION-uv-rye
  before_script:
    - rye config --set [sources].name=gitlab
    - rye config --set [sources].url="https://XXXXXXX/api/v4/projects/XXXXX/packages/pypi/simple"
    - rye config --set [sources].username="gitlab-ci-token"
    - rye config --set [sources].password="$CI_JOB_TOKEN"
    - sed -i 's/\["\[sources\]"\]/\[\[sources\]\]/g' ~/.rye/config.toml
  script:
    - rye sync -f
    - rye test
```

In the `before_script`, I use rye config to set the configuration for the private index, but I have to use sed to replace ["[sources]"] with [[sources]] 😢.

I hope in future releases, rye config will support array config keys or rye sync will add support for --index-url and --extra-index-url.

Still looking for other solutions
