### ISSUE TITLE
Replace pip-tools with Monotrail or Similar

### ISSUE THREAD

**Issue by mitsuhiko** [astral-sh/rye#192]
The use of `pip-tools` in rye is because this is what we use at @getsentry. It's however by no means perfect, among other things it does not have proper locking support and the resolver is very hacky. I would like to investigate alternatives. Options that might exist:

* Use/reuse [pdm](https://github.com/pdm-project/pdm) or it's internals
* [monotrail-resolve](https://github.com/konstin/monotrail-resolve): can resolve, does not lock.

Related issues that this would close:

* #82
* https://github.com/mitsuhiko/rye/issues/200

**Comment by ddelange** [comment]
Hi 👋 

Maybe you find this `Makefile` useful :) it uses pipgrip to to create (and later commit) a lockfile, and then uses that lockfile with pip's `-c/--constraint` flag in `make install` and in our Dockerfile. So the python package just has open version ranges, and the corresponding lockfile lives next to it.

```Makefile
.PHONY: lint
## Run linting
lint:
	pre-commit run --all-files

.PHONY: test
## Run tests
test:
	python -m pytest

.PHONY: install
## Install this repo, plus dev requirements, in editable mode
install:
	test -e requirements/pipgrip.lock || make lockfile
	pip install -r requirements/ci.txt -e . --constraint=requirements/pipgrip.lock
	pre-commit install

.PHONY: lockfile
## Create a lockfile for all python requirements.
lockfile:
	pip install -U pipgrip
	pipgrip -vv --sort --lock --tree .
	mv pipgrip.lock requirements/pipgrip.lock

.PHONY: help
## Print Makefile documentation
help:
	@perl -0 -nle 'printf("%-25s - %s\n", "$$2", "$$1") while m/^##\s*([^\r\n]+)\n^([\w-]+):[^=]/gm' $(MAKEFILE_LIST) | sort
.DEFAULT_GOAL := help
```

in Github Actions, we block PRs if they updated `prod.txt` (which is read into the package's install_requires), but they forgot to run `make lockfile`:

```yaml
    - name: Check whether requirements/prod.txt changed
      id: requirements-changed
      uses: tj-actions/changed-files@v34
      with:
        files: |
          requirements/prod.txt

    - name: Check whether make lockfile was forgotten
      if: steps.requirements-changed.outputs.any_changed == 'true'
      env:
        PIP_INDEX_URL: ${{ secrets.PIP_INDEX_URL }}
      run: |
        make lockfile
        test ! "$(git diff)" && echo "no changes" || ( git diff && exit 1 )
```
