### ISSUE TITLE
Can not install from private registry when using uv

### ISSUE THREAD

**Issue by vhdirk** [astral-sh/rye#802]
### Steps to Reproduce

First off: thanks for this wonderful tool!

I've published a package to a private gitlab index using ci. All of that work perfectly fine.

However, when wanting to use the package in a new project, uv always complains it cannot find it.

I'm using this config file (`~/.rye/config.toml`) :

```toml
[behavior]
use-uv = true

[[sources]]
name = "gitlab-package"
url = "https://gitlab.com/api/v4/projects/my%2Fprivate%2Fpackage/packages/pypi/simple"
username = "__token__"
password = "XXXXXXXXXXXXXXXXXX"
```

then, I want to add it to my project using:

```sh
rye add my-private package
```

### Expected Result

It should fetch the package from the private index

### Actual Result

```sh
rye add mypackage
error: failed to resolve packages:
  × No solution found when resolving dependencies:
  ╰─▶ Because there are no versions of mypackage and you require mypackage, we can
      conclude that the requirements are unsatisfiable.
```

This error seems to come directly from uv: 
```sh
~/.rye/uv/0.1.11/uv pip install mypackage
  × No solution found when resolving dependencies:
  ╰─▶ Because there are no versions of mypackage and you require mypackage, we can conclude that the requirements are unsatisfiable.

```

However, when handing the index-url directly to uv, everything just works:

```sh
~/.rye/uv/0.1.11/uv pip install mypackage --index-url https://__token__:XXXXXXXXXXXXXXXXXX@gitlab.com/api/v4/projects/my%2Fprivate%2Fpackage/packages/pypi/simple
Resolved 15 packages in 2.72s
Installed 1 package in 6ms
 + mypackage==0.1.1

```

So it seems as if rye doesn't hand its sources to uv?

I've repeated these steps with uv _disabled_, and then it works just fine (but it is just soo much slower than with uv :) ).

### Version Info

```
rye  --version
rye 0.27.0
commit: 0.27.0 (43ee4fce0 2024-02-26)
platform: linux (x86_64)
self-python: cpython@3.12
symlink support: true
uv enabled: true
```
