### ISSUE TITLE
Document better how you can reuse optional dependencies (extras) in the dev dependencies

### ISSUE THREAD

**Issue by mathijsvdv** [astral-sh/rye#818]
There's a feature of the `dev-dependencies` that isn't well documented: you can reuse the optional dependencies in the dev dependencies. I sometimes need this when in dev I want to make sure the project is installed including some extras.

At first, I thought I needed to repeat the same dev-dependencies. E.g. to make sure the `anki` dependencies (`anki` and `aqt[qt6]`) are installed, I thought I needed to repeat the dependencies:
```toml
[project.optional-dependencies]
anki = ["anki>=2.1.66", "aqt[qt6]>=2.1.66"]
api = ["fastapi", "fastapi-versionizer", "uvicorn"]

[tool.rye]
dev-dependencies = [
  "anki>=2.1.66", "aqt[qt6]>=2.1.66", "langchain"
]
```

The following doesn't work, so I initially abandoned the idea:
```toml
[project.optional-dependencies]
anki = ["anki>=2.1.66", "aqt[qt6]>=2.1.66"]
api = ["fastapi", "fastapi-versionizer", "uvicorn"]

[tool.rye]
dev-dependencies = [
  ".[anki]", "langchain"
]
```

But after some trial and error, it turns out you can use pip syntax like `-e file:.[extra]` to reuse the optional dependencies in dev.
```toml
[project.optional-dependencies]
anki = ["anki>=2.1.66", "aqt[qt6]>=2.1.66"]
api = ["fastapi", "fastapi-versionizer", "uvicorn"]

[tool.rye]
dev-dependencies = [
  "-e file:.[anki]", "langchain"
]
```

Is this something that can be added to the docs?
