### ISSUE TITLE
`rye run` does not install/show optional dependencies entrypoints

### ISSUE THREAD

**Issue by baggiponte** [astral-sh/rye#835]
### Steps to Reproduce

```
mkdir -p /tmp/reprex
cd $_
rye init
rye add --optional=dev pre-commit pytest pytest-cov
rye run
```

### Expected Result

Rye will list pytest and pre-commit

### Actual Result

![image](https://github.com/astral-sh/rye/assets/57922983/1081e34e-60da-4be5-96e7-dcb0dfaf2a40)

### Version Info

rye --version
rye 0.27.0
commit: 0.27.0 (43ee4fce0 2024-02-26)
platform: macos (aarch64)
self-python: cpython@3.12
symlink support: true
uv enabled: true

My rye config:

```toml
[behavior]
use-uv = true
global-python = true

[default]
toolchain = "cpython@3.10"
```
