### ISSUE TITLE
`rye sync` with uv enabled misses numpy dependency when installing pandas

### ISSUE THREAD

**Issue by Zaloog** [astral-sh/rye#875]
### Steps to Reproduce

1. `rye init project && cd project`
2. `rye pin 3.11.8`
3. `rye add pandas`
4. `rye sync` (not needed if autosync enabled)

Config:
```toml
[default]
# This is the default value that is written into new pyproject.toml
# files for the `project.requires-python` key
requires-python = ">= 3.8"

# This is the default toolchain that is used
toolchain = "cpython@3.11.8"

[behavior]
# Enables global shims when set to `true`.  This means that the installed
# `python` shim will resolve to a Rye managed toolchain even outside of
# virtual environments.
global-python = true

# When set to `true` enables experimental support of uv as a replacement
# for pip-tools. Learn more about uv here: https://github.com/astral-sh/uv
use-uv = true
```

### Expected Result

Pandas and all the dependencies get installed into the .venv

### Actual Result

pandas is added to `pyproject toml` and rye installs the packages. the numpy dependency is missing though
![image](https://github.com/astral-sh/rye/assets/57259263/517dc34e-bc38-40d0-b5a4-74062eeb013b)

Compared to result when pandas is installed with `uv`

![image](https://github.com/astral-sh/rye/assets/57259263/b2a3b6ef-8020-4dc0-92b7-e2a9535376e2)

### Version Info

```
rye 0.29.0
commit: 0.29.0 (42b179f36 2024-03-11)
platform: windows (x86_64)
self-python: cpython@3.12.2
symlink support: false
uv enabled: true
```
