### ISSUE TITLE
dotenv support when use rye run command

### ISSUE THREAD

**Issue by pyfreyr** [astral-sh/rye#885]
Thanks for the great tool and developers!

Is there any plans to support dotenv when use `rye run`?

**Comment by pyfreyr** [comment]
I think a rye's configuration or cli option will be better to meet different needs.

**Comment by pyfreyr** [comment]
`rye test` maybe a example, if auto load dotenv is enabled, inspect `python-dotenv` installed or not.

```sh
$ rye test
error: pytest not installed. Run `rye add --dev pytest`
```

**Comment by PAStheLoD** [comment]
Hello,

Excuse me for piggybacking on this issue instead of opening a new one, but ... currently enterprise-level hello corporate apps are poorly supported, because of the limitation of TOML's inline table (meaning everything has to be on one line, and ... with a few command line arguments and a smattering of chonkier env vars it's so far beyond ridiculous ... it's better to use `env` and one long string instead of trying to table-ify it).

Sure, pyproject.toml is a standard, but this fear of nesting and new lines ... makes me wish for ... `package.json` ... or YAML without the crazy parts.

(Sorry again for the not-really-constructive noise! )

**Comment by mitsuhiko** [comment]
@PAStheLoD i'm not sure I follow on the TOML comment. Can you give an example of the issue you have with TOML?

**Comment by bluss** [comment]
dotenv like support would have good synergy with ryeish-kernel (and it's revamp of it that I'm working on) - it makes it easy to set particular environment variables in the particular jupyter python kernel used - if it applies to `rye run python`.

**Comment by PAStheLoD** [comment]
> @PAStheLoD i'm not sure I follow on the TOML comment. Can you give an example of the issue you have with TOML?

Thanks for taking my semi-unhinged rant seriously. And sorry again for spamming this issue with rather offtopic comments :/

My problem with TOML is that it's impossible to format it nicely, because inline tables cannot contain newlines.

Currently I have this, which is hard to read, and rather unpythonic 😞  (and putting things into a .env file also seems suboptimal, because as the number of scripts increases it would eventually require more .env files.)

```
[tool.rye.scripts]
dev = { cmd = 'python index.py', env = { "mount" = "/api" } }
dev-gunicorn = { cmd = "env huey=0 quiet=0 fast_shutdown=yes app_debug=1 REDIS_PORT=redis://127.0.0.1:6379 MONGO_PORT=mongodb://127.0.0.1:27017/ mount=/api gunicorn --config gunicorn_config.py --bind 0.0.0.0:8080 index:app --reload --workers 1" }

```

It seems that if readability and complex configurability is a concern users will anyway end up with something like django's manage.py (or similar scripts using click and plumbum).

**Comment by mitsuhiko** [comment]
> Currently I have this, which is hard to read, and rather unpythonic 😞 (and putting things into a .env file also seems suboptimal, because as the number of scripts increases it would eventually require more .env files.)

Your particular example can be written like this too if you find this more readable:

```toml
[tool.rye.scripts.dev]
cmd = "python index.py"
env = { "mount" = "/api" }

[tool.rye.scripts.dev-gunicorn]
cmd = ["gunicorn", "--config", "gunicorn_config.py", "--bind", "0.0.0.0:8080", "index:app", "--reload", "--workers 1"]

[tool.rye.scripts.dev-gunicorn.env]
huey = "0"
quiet = "0"
fast_shutdown = "yes"
app_debug = "1"
REDIS_PORT = "redis://127.0.0.1:6379"
MONGO_PORT = "mongodb://127.0.0.1:27017/"
mount = "/api"
```
