### ISSUE TITLE
`project.scripts` not exposed in built sdist or wheel

### ISSUE THREAD

**Issue by liblaf** [astral-sh/rye#899]
### Steps to Reproduce

```toml
# pyproject.toml
[project.scripts]
"hello" = "hello:main"
```

- `rye build`
- `rye install --path dist/hello.tar.gz hello`

### Expected Result

```
Installed scripts:
  - hello
```

### Actual Result

```
installed package did not expose any scripts
```

### Version Info

```
rye 0.29.0
commit: 0.29.0 (42b179f36 2024-03-11)
platform: linux (x86_64)
self-python: cpython@3.12.2
symlink support: true
uv enabled: false
```
