### ISSUE TITLE
✨ Allow passing cwd in `tool.rye.scripts`

### ISSUE THREAD

**Issue by jd-solanki** [astral-sh/rye#930]
Hi 👋🏻 

I'm using `tool.rye.scripts` for running django server from root of the project and it looks like below:
```toml
[tool.rye.scripts]
dev = "python src/django_marketplace/manage.py runserver"
```

## Problem

If I'm already inside `src` dir and run `rye run dev` then it gives error due to incorrect dir I'm in.

## Solution

Provide `cwd` option so we can run rye scripts from anywhere in the project

```toml
dev = { cmd = "python manage.py runserver", cwd: "src/django_marketplace" }
```

Another benefit can be `cmd` option will be much cleaner.
